spring:
  application:
    name: springboot-chat
  datasource:
    username: xxxxxxxxxx
    password: xxxxxxxxxx
    url: jdbc:mysql://127.0.0.1:3306/chat
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
  type-aliases-package: com.afeibaili.chat.pojo